"""Add uid and hashed pwd to user table

Revision ID: 9aeca22d776a
Revises: ab8c012047ad
Create Date: 2024-10-24 18:36:33.261634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9aeca22d776a'
down_revision: Union[str, None] = 'ab8c012047ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('uid', sa.String(length=32), nullable=False))
    op.add_column('user', sa.Column('hashed_password', sa.String(length=21), nullable=False))
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=16),
               nullable=False)
    op.alter_column('user', 'name',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('user', 'city',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('user', 'preferred_language',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('user', 'access_type',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_user_uid'), 'user', ['uid'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_uid'), table_name='user')
    op.alter_column('user', 'access_type',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('user', 'preferred_language',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('user', 'city',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('user', 'name',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('user', 'username',
               existing_type=sa.String(length=16),
               type_=mysql.VARCHAR(length=20),
               nullable=True)
    op.drop_column('user', 'hashed_password')
    op.drop_column('user', 'uid')
    # ### end Alembic commands ###
