"""Update user table

Revision ID: ab8c012047ad
Revises: 4383d2991afc
Create Date: 2024-10-22 00:05:07.955065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ab8c012047ad'
down_revision: Union[str, None] = '4383d2991afc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('user', 'city',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('user', 'birthdate',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('user', 'preferred_language',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('user', 'gender',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('user', 'access_type',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('user', 'photo_path',
               existing_type=mysql.VARCHAR(length=254),
               nullable=True)
    op.drop_index('username', table_name='user')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_index('username', 'user', ['username'], unique=True)
    op.alter_column('user', 'photo_path',
               existing_type=mysql.VARCHAR(length=254),
               nullable=False)
    op.alter_column('user', 'access_type',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('user', 'gender',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('user', 'preferred_language',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('user', 'birthdate',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('user', 'city',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('user', 'name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
